### ISSUE TITLE
Installation failure on Fedora 39 and Python 3.12.2

### ISSUE THREAD

**Issue by teksuo** [aiven/aiven-db-migrate#51]
### Description of the issue
I am trying to install the tool on any of the two proposed ways, but both fail.

### Issue-Type (put a `x` sign in the square brackets)
- [X] bug report
- [ ] feature request
- [X] Documentation improvement
- [ ] Other

### Checklist
- [X] Running latest version of code.
- [X] This issue has not been reported earlier.

### Your environment
* OS
* Python Version
* Release tag/commit of the code

Fedora 39
Python 3.12.2

### Expected behaviour
What should happen?

I am able to run the tool

### Actual behaviour
What is actually happening?

I get the errors described

### Steps to reproduce

1. git clone <>
2. Run any of the two approaches specified in the documentation from the cloned directory.

### Any extra info ( for eg. code snippet to reproduce, logs, screenshots etc. )

After running **make**, I get:

```
echo "__version__ = \"0.1.3-2-g14bbc70\"" > aiven_db_migrate/migrate/version.py
```

After running "**pip install .**", I get:

```bash
Defaulting to user installation because normal site-packages is not writeable
Processing /home/<redacted>/python/aiven-db-migrate
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      Traceback (most recent call last):
        File "/home/rafa/.local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/rafa/.local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/rafa/.local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-__768b88/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-__768b88/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-__768b88/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-__768b88/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 13, in <module>
        File "/tmp/pip-build-env-__768b88/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-__768b88/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "/tmp/pip-build-env-__768b88/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 314, in __init__
          self.metadata.version = self._normalize_version(self.metadata.version)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-__768b88/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 350, in _normalize_version
          normalized = str(Version(version))
                           ^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-__768b88/overlay/lib/python3.12/site-packages/setuptools/_vendor/packaging/version.py", line 198, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: '0.1.3-2-g14bbc70'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

When trying to run the module directly, I get:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/<redacted>/python/aiven-db-migrate/aiven_db_migrate/migrate/__init__.py", line 3, in <module>
    from .pgmigrate import PGMigrate, PGMigrateResult  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<redacted>/python/aiven-db-migrate/aiven_db_migrate/migrate/pgmigrate.py", line 5, in <module>
    from aiven_db_migrate.migrate.pgutils import (
  File "/home/<redacted>/python/aiven-db-migrate/aiven_db_migrate/migrate/pgutils.py", line 7, in <module>
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
```

**Comment by teksuo** [comment]
Manually installing "psycopg2-binary" fixes the module usage, but not the installation.
